/*
 * MantisBT REST API
 * For the sandbox to work, MantisBT must be hosted at the root folder of the host. For example: http://mantishost/ rather http://host/mantisbt.  If that is not the case, then create a host alias to map it as such or edit swagger.json to change basePath to include the mantisbt folder name.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mantis.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.mantis.model.AccessLevel;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.mantis.JSON;

/**
 * CustomField
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-29T22:24:32.148604900+03:00[Europe/Minsk]")
public class CustomField {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_DEFAULT_VALUE = "default_value";
  @SerializedName(SERIALIZED_NAME_DEFAULT_VALUE)
  private String defaultValue;

  public static final String SERIALIZED_NAME_POSSIBLE_VALUES = "possible_values";
  @SerializedName(SERIALIZED_NAME_POSSIBLE_VALUES)
  private String possibleValues;

  public static final String SERIALIZED_NAME_VALID_REGEXP = "valid_regexp";
  @SerializedName(SERIALIZED_NAME_VALID_REGEXP)
  private String validRegexp;

  public static final String SERIALIZED_NAME_LENGTH_MIN = "length_min";
  @SerializedName(SERIALIZED_NAME_LENGTH_MIN)
  private Integer lengthMin;

  public static final String SERIALIZED_NAME_LENGTH_MAX = "length_max";
  @SerializedName(SERIALIZED_NAME_LENGTH_MAX)
  private Integer lengthMax;

  public static final String SERIALIZED_NAME_ACCESS_LEVEL_R = "access_level_r";
  @SerializedName(SERIALIZED_NAME_ACCESS_LEVEL_R)
  private AccessLevel accessLevelR;

  public static final String SERIALIZED_NAME_ACCESS_LEVEL_RW = "access_level_rw";
  @SerializedName(SERIALIZED_NAME_ACCESS_LEVEL_RW)
  private AccessLevel accessLevelRw;

  public static final String SERIALIZED_NAME_DISPLAY_REPORT = "display_report";
  @SerializedName(SERIALIZED_NAME_DISPLAY_REPORT)
  private Boolean displayReport;

  public static final String SERIALIZED_NAME_DISPLAY_UPDATE = "display_update";
  @SerializedName(SERIALIZED_NAME_DISPLAY_UPDATE)
  private Boolean displayUpdate;

  public static final String SERIALIZED_NAME_DISPLAY_RESOLVED = "display_resolved";
  @SerializedName(SERIALIZED_NAME_DISPLAY_RESOLVED)
  private Boolean displayResolved;

  public static final String SERIALIZED_NAME_DISPLAY_CLOSED = "display_closed";
  @SerializedName(SERIALIZED_NAME_DISPLAY_CLOSED)
  private Boolean displayClosed;

  public static final String SERIALIZED_NAME_REQUIRE_REPORT = "require_report";
  @SerializedName(SERIALIZED_NAME_REQUIRE_REPORT)
  private Boolean requireReport;

  public static final String SERIALIZED_NAME_REQUIRE_UPDATE = "require_update";
  @SerializedName(SERIALIZED_NAME_REQUIRE_UPDATE)
  private Boolean requireUpdate;

  public static final String SERIALIZED_NAME_REQUIRE_RESOLVED = "require_resolved";
  @SerializedName(SERIALIZED_NAME_REQUIRE_RESOLVED)
  private Boolean requireResolved;

  public static final String SERIALIZED_NAME_REQUIRE_CLOSED = "require_closed";
  @SerializedName(SERIALIZED_NAME_REQUIRE_CLOSED)
  private Boolean requireClosed;

  public CustomField() {
  }

  public CustomField id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public CustomField name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CustomField type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public CustomField defaultValue(String defaultValue) {
    
    this.defaultValue = defaultValue;
    return this;
  }

   /**
   * Get defaultValue
   * @return defaultValue
  **/
  @javax.annotation.Nullable
  public String getDefaultValue() {
    return defaultValue;
  }


  public void setDefaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
  }


  public CustomField possibleValues(String possibleValues) {
    
    this.possibleValues = possibleValues;
    return this;
  }

   /**
   * Get possibleValues
   * @return possibleValues
  **/
  @javax.annotation.Nullable
  public String getPossibleValues() {
    return possibleValues;
  }


  public void setPossibleValues(String possibleValues) {
    this.possibleValues = possibleValues;
  }


  public CustomField validRegexp(String validRegexp) {
    
    this.validRegexp = validRegexp;
    return this;
  }

   /**
   * Get validRegexp
   * @return validRegexp
  **/
  @javax.annotation.Nullable
  public String getValidRegexp() {
    return validRegexp;
  }


  public void setValidRegexp(String validRegexp) {
    this.validRegexp = validRegexp;
  }


  public CustomField lengthMin(Integer lengthMin) {
    
    this.lengthMin = lengthMin;
    return this;
  }

   /**
   * Get lengthMin
   * @return lengthMin
  **/
  @javax.annotation.Nullable
  public Integer getLengthMin() {
    return lengthMin;
  }


  public void setLengthMin(Integer lengthMin) {
    this.lengthMin = lengthMin;
  }


  public CustomField lengthMax(Integer lengthMax) {
    
    this.lengthMax = lengthMax;
    return this;
  }

   /**
   * Get lengthMax
   * @return lengthMax
  **/
  @javax.annotation.Nullable
  public Integer getLengthMax() {
    return lengthMax;
  }


  public void setLengthMax(Integer lengthMax) {
    this.lengthMax = lengthMax;
  }


  public CustomField accessLevelR(AccessLevel accessLevelR) {
    
    this.accessLevelR = accessLevelR;
    return this;
  }

   /**
   * Get accessLevelR
   * @return accessLevelR
  **/
  @javax.annotation.Nullable
  public AccessLevel getAccessLevelR() {
    return accessLevelR;
  }


  public void setAccessLevelR(AccessLevel accessLevelR) {
    this.accessLevelR = accessLevelR;
  }


  public CustomField accessLevelRw(AccessLevel accessLevelRw) {
    
    this.accessLevelRw = accessLevelRw;
    return this;
  }

   /**
   * Get accessLevelRw
   * @return accessLevelRw
  **/
  @javax.annotation.Nullable
  public AccessLevel getAccessLevelRw() {
    return accessLevelRw;
  }


  public void setAccessLevelRw(AccessLevel accessLevelRw) {
    this.accessLevelRw = accessLevelRw;
  }


  public CustomField displayReport(Boolean displayReport) {
    
    this.displayReport = displayReport;
    return this;
  }

   /**
   * Get displayReport
   * @return displayReport
  **/
  @javax.annotation.Nullable
  public Boolean getDisplayReport() {
    return displayReport;
  }


  public void setDisplayReport(Boolean displayReport) {
    this.displayReport = displayReport;
  }


  public CustomField displayUpdate(Boolean displayUpdate) {
    
    this.displayUpdate = displayUpdate;
    return this;
  }

   /**
   * Get displayUpdate
   * @return displayUpdate
  **/
  @javax.annotation.Nullable
  public Boolean getDisplayUpdate() {
    return displayUpdate;
  }


  public void setDisplayUpdate(Boolean displayUpdate) {
    this.displayUpdate = displayUpdate;
  }


  public CustomField displayResolved(Boolean displayResolved) {
    
    this.displayResolved = displayResolved;
    return this;
  }

   /**
   * Get displayResolved
   * @return displayResolved
  **/
  @javax.annotation.Nullable
  public Boolean getDisplayResolved() {
    return displayResolved;
  }


  public void setDisplayResolved(Boolean displayResolved) {
    this.displayResolved = displayResolved;
  }


  public CustomField displayClosed(Boolean displayClosed) {
    
    this.displayClosed = displayClosed;
    return this;
  }

   /**
   * Get displayClosed
   * @return displayClosed
  **/
  @javax.annotation.Nullable
  public Boolean getDisplayClosed() {
    return displayClosed;
  }


  public void setDisplayClosed(Boolean displayClosed) {
    this.displayClosed = displayClosed;
  }


  public CustomField requireReport(Boolean requireReport) {
    
    this.requireReport = requireReport;
    return this;
  }

   /**
   * Get requireReport
   * @return requireReport
  **/
  @javax.annotation.Nullable
  public Boolean getRequireReport() {
    return requireReport;
  }


  public void setRequireReport(Boolean requireReport) {
    this.requireReport = requireReport;
  }


  public CustomField requireUpdate(Boolean requireUpdate) {
    
    this.requireUpdate = requireUpdate;
    return this;
  }

   /**
   * Get requireUpdate
   * @return requireUpdate
  **/
  @javax.annotation.Nullable
  public Boolean getRequireUpdate() {
    return requireUpdate;
  }


  public void setRequireUpdate(Boolean requireUpdate) {
    this.requireUpdate = requireUpdate;
  }


  public CustomField requireResolved(Boolean requireResolved) {
    
    this.requireResolved = requireResolved;
    return this;
  }

   /**
   * Get requireResolved
   * @return requireResolved
  **/
  @javax.annotation.Nullable
  public Boolean getRequireResolved() {
    return requireResolved;
  }


  public void setRequireResolved(Boolean requireResolved) {
    this.requireResolved = requireResolved;
  }


  public CustomField requireClosed(Boolean requireClosed) {
    
    this.requireClosed = requireClosed;
    return this;
  }

   /**
   * Get requireClosed
   * @return requireClosed
  **/
  @javax.annotation.Nullable
  public Boolean getRequireClosed() {
    return requireClosed;
  }


  public void setRequireClosed(Boolean requireClosed) {
    this.requireClosed = requireClosed;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomField customField = (CustomField) o;
    return Objects.equals(this.id, customField.id) &&
        Objects.equals(this.name, customField.name) &&
        Objects.equals(this.type, customField.type) &&
        Objects.equals(this.defaultValue, customField.defaultValue) &&
        Objects.equals(this.possibleValues, customField.possibleValues) &&
        Objects.equals(this.validRegexp, customField.validRegexp) &&
        Objects.equals(this.lengthMin, customField.lengthMin) &&
        Objects.equals(this.lengthMax, customField.lengthMax) &&
        Objects.equals(this.accessLevelR, customField.accessLevelR) &&
        Objects.equals(this.accessLevelRw, customField.accessLevelRw) &&
        Objects.equals(this.displayReport, customField.displayReport) &&
        Objects.equals(this.displayUpdate, customField.displayUpdate) &&
        Objects.equals(this.displayResolved, customField.displayResolved) &&
        Objects.equals(this.displayClosed, customField.displayClosed) &&
        Objects.equals(this.requireReport, customField.requireReport) &&
        Objects.equals(this.requireUpdate, customField.requireUpdate) &&
        Objects.equals(this.requireResolved, customField.requireResolved) &&
        Objects.equals(this.requireClosed, customField.requireClosed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, type, defaultValue, possibleValues, validRegexp, lengthMin, lengthMax, accessLevelR, accessLevelRw, displayReport, displayUpdate, displayResolved, displayClosed, requireReport, requireUpdate, requireResolved, requireClosed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomField {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    possibleValues: ").append(toIndentedString(possibleValues)).append("\n");
    sb.append("    validRegexp: ").append(toIndentedString(validRegexp)).append("\n");
    sb.append("    lengthMin: ").append(toIndentedString(lengthMin)).append("\n");
    sb.append("    lengthMax: ").append(toIndentedString(lengthMax)).append("\n");
    sb.append("    accessLevelR: ").append(toIndentedString(accessLevelR)).append("\n");
    sb.append("    accessLevelRw: ").append(toIndentedString(accessLevelRw)).append("\n");
    sb.append("    displayReport: ").append(toIndentedString(displayReport)).append("\n");
    sb.append("    displayUpdate: ").append(toIndentedString(displayUpdate)).append("\n");
    sb.append("    displayResolved: ").append(toIndentedString(displayResolved)).append("\n");
    sb.append("    displayClosed: ").append(toIndentedString(displayClosed)).append("\n");
    sb.append("    requireReport: ").append(toIndentedString(requireReport)).append("\n");
    sb.append("    requireUpdate: ").append(toIndentedString(requireUpdate)).append("\n");
    sb.append("    requireResolved: ").append(toIndentedString(requireResolved)).append("\n");
    sb.append("    requireClosed: ").append(toIndentedString(requireClosed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("type");
    openapiFields.add("default_value");
    openapiFields.add("possible_values");
    openapiFields.add("valid_regexp");
    openapiFields.add("length_min");
    openapiFields.add("length_max");
    openapiFields.add("access_level_r");
    openapiFields.add("access_level_rw");
    openapiFields.add("display_report");
    openapiFields.add("display_update");
    openapiFields.add("display_resolved");
    openapiFields.add("display_closed");
    openapiFields.add("require_report");
    openapiFields.add("require_update");
    openapiFields.add("require_resolved");
    openapiFields.add("require_closed");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("type");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CustomField
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CustomField.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CustomField is not found in the empty JSON string", CustomField.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!CustomField.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CustomField` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CustomField.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("default_value") != null && !jsonObj.get("default_value").isJsonNull()) && !jsonObj.get("default_value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `default_value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("default_value").toString()));
      }
      if ((jsonObj.get("possible_values") != null && !jsonObj.get("possible_values").isJsonNull()) && !jsonObj.get("possible_values").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `possible_values` to be a primitive type in the JSON string but got `%s`", jsonObj.get("possible_values").toString()));
      }
      if ((jsonObj.get("valid_regexp") != null && !jsonObj.get("valid_regexp").isJsonNull()) && !jsonObj.get("valid_regexp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `valid_regexp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("valid_regexp").toString()));
      }
      // validate the optional field `access_level_r`
      if (jsonObj.get("access_level_r") != null && !jsonObj.get("access_level_r").isJsonNull()) {
        AccessLevel.validateJsonObject(jsonObj.getAsJsonObject("access_level_r"));
      }
      // validate the optional field `access_level_rw`
      if (jsonObj.get("access_level_rw") != null && !jsonObj.get("access_level_rw").isJsonNull()) {
        AccessLevel.validateJsonObject(jsonObj.getAsJsonObject("access_level_rw"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustomField.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustomField' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustomField> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustomField.class));

       return (TypeAdapter<T>) new TypeAdapter<CustomField>() {
           @Override
           public void write(JsonWriter out, CustomField value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CustomField read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CustomField given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CustomField
  * @throws IOException if the JSON string is invalid with respect to CustomField
  */
  public static CustomField fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustomField.class);
  }

 /**
  * Convert an instance of CustomField to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

