/*
 * MantisBT REST API
 * For the sandbox to work, MantisBT must be hosted at the root folder of the host. For example: http://mantishost/ rather http://host/mantisbt.  If that is not the case, then create a host alias to map it as such or edit swagger.json to change basePath to include the mantisbt folder name.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mantis.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.mantis.model.AccountRef;
import org.mantis.model.Identifier;
import org.mantis.model.UploadableFile;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.mantis.JSON;

/**
 * Issue
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-26T00:05:27.509810400+03:00[Europe/Minsk]", comments = "Generator version: 7.19.0")
public class Issue {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Long id;

  public static final String SERIALIZED_NAME_PROJECT = "project";
  @SerializedName(SERIALIZED_NAME_PROJECT)
  @javax.annotation.Nonnull
  private Identifier project;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  @javax.annotation.Nullable
  private Identifier category;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  @javax.annotation.Nullable
  private Identifier priority;

  public static final String SERIALIZED_NAME_SEVERITY = "severity";
  @SerializedName(SERIALIZED_NAME_SEVERITY)
  @javax.annotation.Nullable
  private Identifier severity;

  public static final String SERIALIZED_NAME_REPRODUCIBILITY = "reproducibility";
  @SerializedName(SERIALIZED_NAME_REPRODUCIBILITY)
  @javax.annotation.Nullable
  private Identifier reproducibility;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nullable
  private Identifier version;

  public static final String SERIALIZED_NAME_OS = "os";
  @SerializedName(SERIALIZED_NAME_OS)
  @javax.annotation.Nullable
  private String os;

  public static final String SERIALIZED_NAME_OS_BUILD = "os_build";
  @SerializedName(SERIALIZED_NAME_OS_BUILD)
  @javax.annotation.Nullable
  private String osBuild;

  public static final String SERIALIZED_NAME_PLATFORM = "platform";
  @SerializedName(SERIALIZED_NAME_PLATFORM)
  @javax.annotation.Nullable
  private String platform;

  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  @javax.annotation.Nonnull
  private String summary;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nonnull
  private String description;

  public static final String SERIALIZED_NAME_STEPS_TO_REPRODUCE = "steps_to_reproduce";
  @SerializedName(SERIALIZED_NAME_STEPS_TO_REPRODUCE)
  @javax.annotation.Nullable
  private String stepsToReproduce;

  public static final String SERIALIZED_NAME_ADDITIONAL_INFORMATION = "additional_information";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_INFORMATION)
  @javax.annotation.Nullable
  private String additionalInformation;

  public static final String SERIALIZED_NAME_REPORTER = "reporter";
  @SerializedName(SERIALIZED_NAME_REPORTER)
  @javax.annotation.Nullable
  private AccountRef reporter;

  public static final String SERIALIZED_NAME_HANDLER = "handler";
  @SerializedName(SERIALIZED_NAME_HANDLER)
  @javax.annotation.Nullable
  private AccountRef handler;

  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  @javax.annotation.Nullable
  private List<UploadableFile> files = new ArrayList<>();

  public Issue() {
  }

  public Issue id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public Issue project(@javax.annotation.Nonnull Identifier project) {
    this.project = project;
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @javax.annotation.Nonnull
  public Identifier getProject() {
    return project;
  }

  public void setProject(@javax.annotation.Nonnull Identifier project) {
    this.project = project;
  }


  public Issue category(@javax.annotation.Nullable Identifier category) {
    this.category = category;
    return this;
  }

  /**
   * Get category
   * @return category
   */
  @javax.annotation.Nullable
  public Identifier getCategory() {
    return category;
  }

  public void setCategory(@javax.annotation.Nullable Identifier category) {
    this.category = category;
  }


  public Issue priority(@javax.annotation.Nullable Identifier priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Get priority
   * @return priority
   */
  @javax.annotation.Nullable
  public Identifier getPriority() {
    return priority;
  }

  public void setPriority(@javax.annotation.Nullable Identifier priority) {
    this.priority = priority;
  }


  public Issue severity(@javax.annotation.Nullable Identifier severity) {
    this.severity = severity;
    return this;
  }

  /**
   * Get severity
   * @return severity
   */
  @javax.annotation.Nullable
  public Identifier getSeverity() {
    return severity;
  }

  public void setSeverity(@javax.annotation.Nullable Identifier severity) {
    this.severity = severity;
  }


  public Issue reproducibility(@javax.annotation.Nullable Identifier reproducibility) {
    this.reproducibility = reproducibility;
    return this;
  }

  /**
   * Get reproducibility
   * @return reproducibility
   */
  @javax.annotation.Nullable
  public Identifier getReproducibility() {
    return reproducibility;
  }

  public void setReproducibility(@javax.annotation.Nullable Identifier reproducibility) {
    this.reproducibility = reproducibility;
  }


  public Issue version(@javax.annotation.Nullable Identifier version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  public Identifier getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nullable Identifier version) {
    this.version = version;
  }


  public Issue os(@javax.annotation.Nullable String os) {
    this.os = os;
    return this;
  }

  /**
   * Get os
   * @return os
   */
  @javax.annotation.Nullable
  public String getOs() {
    return os;
  }

  public void setOs(@javax.annotation.Nullable String os) {
    this.os = os;
  }


  public Issue osBuild(@javax.annotation.Nullable String osBuild) {
    this.osBuild = osBuild;
    return this;
  }

  /**
   * Get osBuild
   * @return osBuild
   */
  @javax.annotation.Nullable
  public String getOsBuild() {
    return osBuild;
  }

  public void setOsBuild(@javax.annotation.Nullable String osBuild) {
    this.osBuild = osBuild;
  }


  public Issue platform(@javax.annotation.Nullable String platform) {
    this.platform = platform;
    return this;
  }

  /**
   * Get platform
   * @return platform
   */
  @javax.annotation.Nullable
  public String getPlatform() {
    return platform;
  }

  public void setPlatform(@javax.annotation.Nullable String platform) {
    this.platform = platform;
  }


  public Issue summary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @javax.annotation.Nonnull
  public String getSummary() {
    return summary;
  }

  public void setSummary(@javax.annotation.Nonnull String summary) {
    this.summary = summary;
  }


  public Issue description(@javax.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }


  public Issue stepsToReproduce(@javax.annotation.Nullable String stepsToReproduce) {
    this.stepsToReproduce = stepsToReproduce;
    return this;
  }

  /**
   * Get stepsToReproduce
   * @return stepsToReproduce
   */
  @javax.annotation.Nullable
  public String getStepsToReproduce() {
    return stepsToReproduce;
  }

  public void setStepsToReproduce(@javax.annotation.Nullable String stepsToReproduce) {
    this.stepsToReproduce = stepsToReproduce;
  }


  public Issue additionalInformation(@javax.annotation.Nullable String additionalInformation) {
    this.additionalInformation = additionalInformation;
    return this;
  }

  /**
   * Get additionalInformation
   * @return additionalInformation
   */
  @javax.annotation.Nullable
  public String getAdditionalInformation() {
    return additionalInformation;
  }

  public void setAdditionalInformation(@javax.annotation.Nullable String additionalInformation) {
    this.additionalInformation = additionalInformation;
  }


  public Issue reporter(@javax.annotation.Nullable AccountRef reporter) {
    this.reporter = reporter;
    return this;
  }

  /**
   * Get reporter
   * @return reporter
   */
  @javax.annotation.Nullable
  public AccountRef getReporter() {
    return reporter;
  }

  public void setReporter(@javax.annotation.Nullable AccountRef reporter) {
    this.reporter = reporter;
  }


  public Issue handler(@javax.annotation.Nullable AccountRef handler) {
    this.handler = handler;
    return this;
  }

  /**
   * Get handler
   * @return handler
   */
  @javax.annotation.Nullable
  public AccountRef getHandler() {
    return handler;
  }

  public void setHandler(@javax.annotation.Nullable AccountRef handler) {
    this.handler = handler;
  }


  public Issue files(@javax.annotation.Nullable List<UploadableFile> files) {
    this.files = files;
    return this;
  }

  public Issue addFilesItem(UploadableFile filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

  /**
   * Get files
   * @return files
   */
  @javax.annotation.Nullable
  public List<UploadableFile> getFiles() {
    return files;
  }

  public void setFiles(@javax.annotation.Nullable List<UploadableFile> files) {
    this.files = files;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Issue issue = (Issue) o;
    return Objects.equals(this.id, issue.id) &&
        Objects.equals(this.project, issue.project) &&
        Objects.equals(this.category, issue.category) &&
        Objects.equals(this.priority, issue.priority) &&
        Objects.equals(this.severity, issue.severity) &&
        Objects.equals(this.reproducibility, issue.reproducibility) &&
        Objects.equals(this.version, issue.version) &&
        Objects.equals(this.os, issue.os) &&
        Objects.equals(this.osBuild, issue.osBuild) &&
        Objects.equals(this.platform, issue.platform) &&
        Objects.equals(this.summary, issue.summary) &&
        Objects.equals(this.description, issue.description) &&
        Objects.equals(this.stepsToReproduce, issue.stepsToReproduce) &&
        Objects.equals(this.additionalInformation, issue.additionalInformation) &&
        Objects.equals(this.reporter, issue.reporter) &&
        Objects.equals(this.handler, issue.handler) &&
        Objects.equals(this.files, issue.files);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, project, category, priority, severity, reproducibility, version, os, osBuild, platform, summary, description, stepsToReproduce, additionalInformation, reporter, handler, files);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Issue {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    reproducibility: ").append(toIndentedString(reproducibility)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    osBuild: ").append(toIndentedString(osBuild)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    stepsToReproduce: ").append(toIndentedString(stepsToReproduce)).append("\n");
    sb.append("    additionalInformation: ").append(toIndentedString(additionalInformation)).append("\n");
    sb.append("    reporter: ").append(toIndentedString(reporter)).append("\n");
    sb.append("    handler: ").append(toIndentedString(handler)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "project", "category", "priority", "severity", "reproducibility", "version", "os", "os_build", "platform", "summary", "description", "steps_to_reproduce", "additional_information", "reporter", "handler", "files"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("project", "summary", "description"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Issue
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Issue.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Issue is not found in the empty JSON string", Issue.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Issue.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Issue` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Issue.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `project`
      Identifier.validateJsonElement(jsonObj.get("project"));
      // validate the optional field `category`
      if (jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) {
        Identifier.validateJsonElement(jsonObj.get("category"));
      }
      // validate the optional field `priority`
      if (jsonObj.get("priority") != null && !jsonObj.get("priority").isJsonNull()) {
        Identifier.validateJsonElement(jsonObj.get("priority"));
      }
      // validate the optional field `severity`
      if (jsonObj.get("severity") != null && !jsonObj.get("severity").isJsonNull()) {
        Identifier.validateJsonElement(jsonObj.get("severity"));
      }
      // validate the optional field `reproducibility`
      if (jsonObj.get("reproducibility") != null && !jsonObj.get("reproducibility").isJsonNull()) {
        Identifier.validateJsonElement(jsonObj.get("reproducibility"));
      }
      // validate the optional field `version`
      if (jsonObj.get("version") != null && !jsonObj.get("version").isJsonNull()) {
        Identifier.validateJsonElement(jsonObj.get("version"));
      }
      if ((jsonObj.get("os") != null && !jsonObj.get("os").isJsonNull()) && !jsonObj.get("os").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `os` to be a primitive type in the JSON string but got `%s`", jsonObj.get("os").toString()));
      }
      if ((jsonObj.get("os_build") != null && !jsonObj.get("os_build").isJsonNull()) && !jsonObj.get("os_build").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `os_build` to be a primitive type in the JSON string but got `%s`", jsonObj.get("os_build").toString()));
      }
      if ((jsonObj.get("platform") != null && !jsonObj.get("platform").isJsonNull()) && !jsonObj.get("platform").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `platform` to be a primitive type in the JSON string but got `%s`", jsonObj.get("platform").toString()));
      }
      if (!jsonObj.get("summary").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `summary` to be a primitive type in the JSON string but got `%s`", jsonObj.get("summary").toString()));
      }
      if (!jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("steps_to_reproduce") != null && !jsonObj.get("steps_to_reproduce").isJsonNull()) && !jsonObj.get("steps_to_reproduce").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `steps_to_reproduce` to be a primitive type in the JSON string but got `%s`", jsonObj.get("steps_to_reproduce").toString()));
      }
      if ((jsonObj.get("additional_information") != null && !jsonObj.get("additional_information").isJsonNull()) && !jsonObj.get("additional_information").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `additional_information` to be a primitive type in the JSON string but got `%s`", jsonObj.get("additional_information").toString()));
      }
      // validate the optional field `reporter`
      if (jsonObj.get("reporter") != null && !jsonObj.get("reporter").isJsonNull()) {
        AccountRef.validateJsonElement(jsonObj.get("reporter"));
      }
      // validate the optional field `handler`
      if (jsonObj.get("handler") != null && !jsonObj.get("handler").isJsonNull()) {
        AccountRef.validateJsonElement(jsonObj.get("handler"));
      }
      if (jsonObj.get("files") != null && !jsonObj.get("files").isJsonNull()) {
        JsonArray jsonArrayfiles = jsonObj.getAsJsonArray("files");
        if (jsonArrayfiles != null) {
          // ensure the json data is an array
          if (!jsonObj.get("files").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `files` to be an array in the JSON string but got `%s`", jsonObj.get("files").toString()));
          }

          // validate the optional field `files` (array)
          for (int i = 0; i < jsonArrayfiles.size(); i++) {
            UploadableFile.validateJsonElement(jsonArrayfiles.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Issue.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Issue' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Issue> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Issue.class));

       return (TypeAdapter<T>) new TypeAdapter<Issue>() {
           @Override
           public void write(JsonWriter out, Issue value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Issue read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Issue given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Issue
   * @throws IOException if the JSON string is invalid with respect to Issue
   */
  public static Issue fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Issue.class);
  }

  /**
   * Convert an instance of Issue to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

