/*
 * MantisBT REST API
 * For the sandbox to work, MantisBT must be hosted at the root folder of the host. For example: http://mantishost/ rather http://host/mantisbt.  If that is not the case, then create a host alias to map it as such or edit swagger.json to change basePath to include the mantisbt folder name.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mantis.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.mantis.model.AccountRef;
import org.mantis.model.Identifier;
import org.mantis.model.UploadableFile;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.mantis.JSON;

/**
 * Issue
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-29T22:24:32.148604900+03:00[Europe/Minsk]")
public class Issue {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_PROJECT = "project";
  @SerializedName(SERIALIZED_NAME_PROJECT)
  private Identifier project;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private Identifier category;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Identifier priority;

  public static final String SERIALIZED_NAME_SEVERITY = "severity";
  @SerializedName(SERIALIZED_NAME_SEVERITY)
  private Identifier severity;

  public static final String SERIALIZED_NAME_REPRODUCIBILITY = "reproducibility";
  @SerializedName(SERIALIZED_NAME_REPRODUCIBILITY)
  private Identifier reproducibility;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Identifier version;

  public static final String SERIALIZED_NAME_OS = "os";
  @SerializedName(SERIALIZED_NAME_OS)
  private String os;

  public static final String SERIALIZED_NAME_OS_BUILD = "os_build";
  @SerializedName(SERIALIZED_NAME_OS_BUILD)
  private String osBuild;

  public static final String SERIALIZED_NAME_PLATFORM = "platform";
  @SerializedName(SERIALIZED_NAME_PLATFORM)
  private String platform;

  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  private String summary;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_STEPS_TO_REPRODUCE = "steps_to_reproduce";
  @SerializedName(SERIALIZED_NAME_STEPS_TO_REPRODUCE)
  private String stepsToReproduce;

  public static final String SERIALIZED_NAME_ADDITIONAL_INFORMATION = "additional_information";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_INFORMATION)
  private String additionalInformation;

  public static final String SERIALIZED_NAME_REPORTER = "reporter";
  @SerializedName(SERIALIZED_NAME_REPORTER)
  private AccountRef reporter;

  public static final String SERIALIZED_NAME_HANDLER = "handler";
  @SerializedName(SERIALIZED_NAME_HANDLER)
  private AccountRef handler;

  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  private List<UploadableFile> files;

  public Issue() {
  }

  public Issue id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public Issue project(Identifier project) {
    
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @javax.annotation.Nonnull
  public Identifier getProject() {
    return project;
  }


  public void setProject(Identifier project) {
    this.project = project;
  }


  public Issue category(Identifier category) {
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @javax.annotation.Nullable
  public Identifier getCategory() {
    return category;
  }


  public void setCategory(Identifier category) {
    this.category = category;
  }


  public Issue priority(Identifier priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @javax.annotation.Nullable
  public Identifier getPriority() {
    return priority;
  }


  public void setPriority(Identifier priority) {
    this.priority = priority;
  }


  public Issue severity(Identifier severity) {
    
    this.severity = severity;
    return this;
  }

   /**
   * Get severity
   * @return severity
  **/
  @javax.annotation.Nullable
  public Identifier getSeverity() {
    return severity;
  }


  public void setSeverity(Identifier severity) {
    this.severity = severity;
  }


  public Issue reproducibility(Identifier reproducibility) {
    
    this.reproducibility = reproducibility;
    return this;
  }

   /**
   * Get reproducibility
   * @return reproducibility
  **/
  @javax.annotation.Nullable
  public Identifier getReproducibility() {
    return reproducibility;
  }


  public void setReproducibility(Identifier reproducibility) {
    this.reproducibility = reproducibility;
  }


  public Issue version(Identifier version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  public Identifier getVersion() {
    return version;
  }


  public void setVersion(Identifier version) {
    this.version = version;
  }


  public Issue os(String os) {
    
    this.os = os;
    return this;
  }

   /**
   * Get os
   * @return os
  **/
  @javax.annotation.Nullable
  public String getOs() {
    return os;
  }


  public void setOs(String os) {
    this.os = os;
  }


  public Issue osBuild(String osBuild) {
    
    this.osBuild = osBuild;
    return this;
  }

   /**
   * Get osBuild
   * @return osBuild
  **/
  @javax.annotation.Nullable
  public String getOsBuild() {
    return osBuild;
  }


  public void setOsBuild(String osBuild) {
    this.osBuild = osBuild;
  }


  public Issue platform(String platform) {
    
    this.platform = platform;
    return this;
  }

   /**
   * Get platform
   * @return platform
  **/
  @javax.annotation.Nullable
  public String getPlatform() {
    return platform;
  }


  public void setPlatform(String platform) {
    this.platform = platform;
  }


  public Issue summary(String summary) {
    
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @javax.annotation.Nonnull
  public String getSummary() {
    return summary;
  }


  public void setSummary(String summary) {
    this.summary = summary;
  }


  public Issue description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public Issue stepsToReproduce(String stepsToReproduce) {
    
    this.stepsToReproduce = stepsToReproduce;
    return this;
  }

   /**
   * Get stepsToReproduce
   * @return stepsToReproduce
  **/
  @javax.annotation.Nullable
  public String getStepsToReproduce() {
    return stepsToReproduce;
  }


  public void setStepsToReproduce(String stepsToReproduce) {
    this.stepsToReproduce = stepsToReproduce;
  }


  public Issue additionalInformation(String additionalInformation) {
    
    this.additionalInformation = additionalInformation;
    return this;
  }

   /**
   * Get additionalInformation
   * @return additionalInformation
  **/
  @javax.annotation.Nullable
  public String getAdditionalInformation() {
    return additionalInformation;
  }


  public void setAdditionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation;
  }


  public Issue reporter(AccountRef reporter) {
    
    this.reporter = reporter;
    return this;
  }

   /**
   * Get reporter
   * @return reporter
  **/
  @javax.annotation.Nullable
  public AccountRef getReporter() {
    return reporter;
  }


  public void setReporter(AccountRef reporter) {
    this.reporter = reporter;
  }


  public Issue handler(AccountRef handler) {
    
    this.handler = handler;
    return this;
  }

   /**
   * Get handler
   * @return handler
  **/
  @javax.annotation.Nullable
  public AccountRef getHandler() {
    return handler;
  }


  public void setHandler(AccountRef handler) {
    this.handler = handler;
  }


  public Issue files(List<UploadableFile> files) {
    
    this.files = files;
    return this;
  }

  public Issue addFilesItem(UploadableFile filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @javax.annotation.Nullable
  public List<UploadableFile> getFiles() {
    return files;
  }


  public void setFiles(List<UploadableFile> files) {
    this.files = files;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Issue issue = (Issue) o;
    return Objects.equals(this.id, issue.id) &&
        Objects.equals(this.project, issue.project) &&
        Objects.equals(this.category, issue.category) &&
        Objects.equals(this.priority, issue.priority) &&
        Objects.equals(this.severity, issue.severity) &&
        Objects.equals(this.reproducibility, issue.reproducibility) &&
        Objects.equals(this.version, issue.version) &&
        Objects.equals(this.os, issue.os) &&
        Objects.equals(this.osBuild, issue.osBuild) &&
        Objects.equals(this.platform, issue.platform) &&
        Objects.equals(this.summary, issue.summary) &&
        Objects.equals(this.description, issue.description) &&
        Objects.equals(this.stepsToReproduce, issue.stepsToReproduce) &&
        Objects.equals(this.additionalInformation, issue.additionalInformation) &&
        Objects.equals(this.reporter, issue.reporter) &&
        Objects.equals(this.handler, issue.handler) &&
        Objects.equals(this.files, issue.files);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, project, category, priority, severity, reproducibility, version, os, osBuild, platform, summary, description, stepsToReproduce, additionalInformation, reporter, handler, files);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Issue {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    reproducibility: ").append(toIndentedString(reproducibility)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    osBuild: ").append(toIndentedString(osBuild)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    stepsToReproduce: ").append(toIndentedString(stepsToReproduce)).append("\n");
    sb.append("    additionalInformation: ").append(toIndentedString(additionalInformation)).append("\n");
    sb.append("    reporter: ").append(toIndentedString(reporter)).append("\n");
    sb.append("    handler: ").append(toIndentedString(handler)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("project");
    openapiFields.add("category");
    openapiFields.add("priority");
    openapiFields.add("severity");
    openapiFields.add("reproducibility");
    openapiFields.add("version");
    openapiFields.add("os");
    openapiFields.add("os_build");
    openapiFields.add("platform");
    openapiFields.add("summary");
    openapiFields.add("description");
    openapiFields.add("steps_to_reproduce");
    openapiFields.add("additional_information");
    openapiFields.add("reporter");
    openapiFields.add("handler");
    openapiFields.add("files");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("project");
    openapiRequiredFields.add("summary");
    openapiRequiredFields.add("description");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Issue
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Issue.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Issue is not found in the empty JSON string", Issue.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Issue.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Issue` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Issue.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the required field `project`
      Identifier.validateJsonObject(jsonObj.getAsJsonObject("project"));
      // validate the optional field `category`
      if (jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) {
        Identifier.validateJsonObject(jsonObj.getAsJsonObject("category"));
      }
      // validate the optional field `priority`
      if (jsonObj.get("priority") != null && !jsonObj.get("priority").isJsonNull()) {
        Identifier.validateJsonObject(jsonObj.getAsJsonObject("priority"));
      }
      // validate the optional field `severity`
      if (jsonObj.get("severity") != null && !jsonObj.get("severity").isJsonNull()) {
        Identifier.validateJsonObject(jsonObj.getAsJsonObject("severity"));
      }
      // validate the optional field `reproducibility`
      if (jsonObj.get("reproducibility") != null && !jsonObj.get("reproducibility").isJsonNull()) {
        Identifier.validateJsonObject(jsonObj.getAsJsonObject("reproducibility"));
      }
      // validate the optional field `version`
      if (jsonObj.get("version") != null && !jsonObj.get("version").isJsonNull()) {
        Identifier.validateJsonObject(jsonObj.getAsJsonObject("version"));
      }
      if ((jsonObj.get("os") != null && !jsonObj.get("os").isJsonNull()) && !jsonObj.get("os").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `os` to be a primitive type in the JSON string but got `%s`", jsonObj.get("os").toString()));
      }
      if ((jsonObj.get("os_build") != null && !jsonObj.get("os_build").isJsonNull()) && !jsonObj.get("os_build").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `os_build` to be a primitive type in the JSON string but got `%s`", jsonObj.get("os_build").toString()));
      }
      if ((jsonObj.get("platform") != null && !jsonObj.get("platform").isJsonNull()) && !jsonObj.get("platform").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `platform` to be a primitive type in the JSON string but got `%s`", jsonObj.get("platform").toString()));
      }
      if (!jsonObj.get("summary").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `summary` to be a primitive type in the JSON string but got `%s`", jsonObj.get("summary").toString()));
      }
      if (!jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("steps_to_reproduce") != null && !jsonObj.get("steps_to_reproduce").isJsonNull()) && !jsonObj.get("steps_to_reproduce").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `steps_to_reproduce` to be a primitive type in the JSON string but got `%s`", jsonObj.get("steps_to_reproduce").toString()));
      }
      if ((jsonObj.get("additional_information") != null && !jsonObj.get("additional_information").isJsonNull()) && !jsonObj.get("additional_information").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `additional_information` to be a primitive type in the JSON string but got `%s`", jsonObj.get("additional_information").toString()));
      }
      // validate the optional field `reporter`
      if (jsonObj.get("reporter") != null && !jsonObj.get("reporter").isJsonNull()) {
        AccountRef.validateJsonObject(jsonObj.getAsJsonObject("reporter"));
      }
      // validate the optional field `handler`
      if (jsonObj.get("handler") != null && !jsonObj.get("handler").isJsonNull()) {
        AccountRef.validateJsonObject(jsonObj.getAsJsonObject("handler"));
      }
      if (jsonObj.get("files") != null && !jsonObj.get("files").isJsonNull()) {
        JsonArray jsonArrayfiles = jsonObj.getAsJsonArray("files");
        if (jsonArrayfiles != null) {
          // ensure the json data is an array
          if (!jsonObj.get("files").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `files` to be an array in the JSON string but got `%s`", jsonObj.get("files").toString()));
          }

          // validate the optional field `files` (array)
          for (int i = 0; i < jsonArrayfiles.size(); i++) {
            UploadableFile.validateJsonObject(jsonArrayfiles.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Issue.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Issue' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Issue> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Issue.class));

       return (TypeAdapter<T>) new TypeAdapter<Issue>() {
           @Override
           public void write(JsonWriter out, Issue value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Issue read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Issue given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Issue
  * @throws IOException if the JSON string is invalid with respect to Issue
  */
  public static Issue fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Issue.class);
  }

 /**
  * Convert an instance of Issue to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

