/*
 * MantisBT REST API
 * For the sandbox to work, MantisBT must be hosted at the root folder of the host. For example: http://mantishost/ rather http://host/mantisbt.  If that is not the case, then create a host alias to map it as such or edit swagger.json to change basePath to include the mantisbt folder name.
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.mantis.api;

import org.mantis.ApiCallback;
import org.mantis.ApiClient;
import org.mantis.ApiException;
import org.mantis.ApiResponse;
import org.mantis.Configuration;
import org.mantis.Pair;
import org.mantis.ProgressRequestBody;
import org.mantis.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.mantis.model.ConfigGetResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class ConfigApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ConfigApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ConfigApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for configGet
     * @param option An array of configuration options. (required)
     * @param projectId The project id (default All Projects). (optional)
     * @param userId The user id (default is logged in user).  This can only be set by users with access level ADMINISTRATOR. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Access denied </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> User or Project not found </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Mantis Offline </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call configGetCall(List<String> option, Long projectId, Long userId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/config";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (option != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("csv", "option", option));
        }

        if (projectId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("project_id", projectId));
        }

        if (userId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("user_id", userId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call configGetValidateBeforeCall(List<String> option, Long projectId, Long userId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'option' is set
        if (option == null) {
            throw new ApiException("Missing the required parameter 'option' when calling configGet(Async)");
        }

        return configGetCall(option, projectId, userId, _callback);

    }

    /**
     * Get config options
     * Get the value for a set of configuration options given a user and project context.  If a configuration option is invalid or is marked as private, then they will be filtered out, but request will still succeed.
     * @param option An array of configuration options. (required)
     * @param projectId The project id (default All Projects). (optional)
     * @param userId The user id (default is logged in user).  This can only be set by users with access level ADMINISTRATOR. (optional)
     * @return ConfigGetResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Access denied </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> User or Project not found </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Mantis Offline </td><td>  -  </td></tr>
     </table>
     */
    public ConfigGetResponse configGet(List<String> option, Long projectId, Long userId) throws ApiException {
        ApiResponse<ConfigGetResponse> localVarResp = configGetWithHttpInfo(option, projectId, userId);
        return localVarResp.getData();
    }

    /**
     * Get config options
     * Get the value for a set of configuration options given a user and project context.  If a configuration option is invalid or is marked as private, then they will be filtered out, but request will still succeed.
     * @param option An array of configuration options. (required)
     * @param projectId The project id (default All Projects). (optional)
     * @param userId The user id (default is logged in user).  This can only be set by users with access level ADMINISTRATOR. (optional)
     * @return ApiResponse&lt;ConfigGetResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Access denied </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> User or Project not found </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Mantis Offline </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ConfigGetResponse> configGetWithHttpInfo(List<String> option, Long projectId, Long userId) throws ApiException {
        okhttp3.Call localVarCall = configGetValidateBeforeCall(option, projectId, userId, null);
        Type localVarReturnType = new TypeToken<ConfigGetResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get config options (asynchronously)
     * Get the value for a set of configuration options given a user and project context.  If a configuration option is invalid or is marked as private, then they will be filtered out, but request will still succeed.
     * @param option An array of configuration options. (required)
     * @param projectId The project id (default All Projects). (optional)
     * @param userId The user id (default is logged in user).  This can only be set by users with access level ADMINISTRATOR. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Access denied </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> User or Project not found </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Mantis Offline </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call configGetAsync(List<String> option, Long projectId, Long userId, final ApiCallback<ConfigGetResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = configGetValidateBeforeCall(option, projectId, userId, _callback);
        Type localVarReturnType = new TypeToken<ConfigGetResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
